/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  darkMode: ["class", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        // Semantic theme-aware colors (all reference CSS custom properties)
        surface: "var(--bg-primary)",
        "surface-2": "var(--bg-secondary)",
        "surface-3": "var(--bg-tertiary)",
        "surface-card": "var(--bg-card)",
        "surface-input": "var(--bg-input)",
        sidebar: "var(--bg-sidebar)",
        "sidebar-hover": "var(--bg-sidebar-hover)",
        "sidebar-active": "var(--bg-sidebar-active)",
        "text-1": "var(--text-primary)",
        "text-2": "var(--text-secondary)",
        "text-3": "var(--text-tertiary)",
        "text-sidebar": "var(--text-sidebar)",
        accent: "var(--accent)",
        "accent-hover": "var(--accent-hover)",
        "accent-light": "var(--accent-light)",
        "accent-2": "var(--accent-secondary)",
        danger: "var(--danger)",
        "danger-hover": "var(--danger-hover)",
        success: "var(--success)",
        "success-bg": "var(--success-bg)",
        warning: "var(--warning)",
        "warning-bg": "var(--warning-bg)",
        info: "var(--info)",
        "info-bg": "var(--info-bg)",
        border: "var(--border-primary)",
        "border-2": "var(--border-secondary)",
        "border-focus": "var(--border-focus)",
        "user-msg": "var(--bg-user-msg)",
        "bot-msg": "var(--bg-bot-msg)",
        upload: "var(--bg-upload)",
        "upload-border": "var(--bg-upload-border)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        DEFAULT: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
      },
      boxShadow: {
        sm: "var(--shadow-sm)",
        DEFAULT: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        xl: "var(--shadow-xl)",
      },
      fontFamily: {
        sans: [
          '"Segoe UI"',
          "-apple-system",
          "BlinkMacSystemFont",
          "Inter",
          "sans-serif",
        ],
      },
    },
  },
  plugins: [],
};
